openapi: 3.0.0
info:
  title: UdaConnect Person API
  version: 1.0.0
  description: API for managing persons.
servers:
  - url: http://localhost:30001
paths:
  /api/persons:
    post:
      summary: Create a new person
      operationId: createPerson
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: The first name of the person
                  example: John
                last_name:
                  type: string
                  description: The last name of the person
                  example: Doe
                company_name:
                  type: string
                  description: The company name of the person
                  example: Acme Corp
      responses:
        '201':
          description: Person created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The unique identifier of the person
                    example: 1
                  first_name:
                    type: string
                    example: John
                  last_name:
                    type: string
                    example: Doe
                  company_name:
                    type: string
                    example: Acme Corp
        '400':
          description: Invalid input

    get:
      summary: Retrieve all persons
      operationId: getPersons
      responses:
        '200':
          description: A list of persons
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The unique identifier of the person
                      example: 1
                    first_name:
                      type: string
                      example: John
                    last_name:
                      type: string
                      example: Doe
                    company_name:
                      type: string
                      example: Acme Corp

  /api/persons/{person_id}:
    get:
      summary: Retrieve a person by ID
      operationId: getPersonById
      parameters:
        - name: person_id
          in: path
          required: true
          description: Unique ID for a given Person
          schema:
            type: integer
      responses:
        '200':
          description: A person object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The unique identifier of the person
                    example: 1
                  first_name:
                    type: string
                    example: John
                  last_name:
                    type: string
                    example: Doe
                  company_name:
                    type: string
                    example: Acme Corp
        '404':
          description: Person not found
