apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-frontend
  name: udaconnect-frontend
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    service: udaconnect-frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-frontend
  name: udaconnect-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-frontend
  template:
    metadata:
      labels:
        service: udaconnect-frontend
    spec:
      containers:
      - image: wing0805/message-passing-frontend:latest
        name: udaconnect-frontend
        imagePullPolicy: Always
        env:
        - name: PERSON_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-env
              key: PERSON_API_BASE_URL
        - name: CONNECTION_API_BASE_URL
          valueFrom:
            secretKeyRef:
              name: frontend-env
              key: CONNECTION_API_BASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always