apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_geoconnections"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres-geoconnections"
  DB_PORT: "5432"
  KAFKA_SERVER: my-kafka-controller-0.my-kafka-controller-headless.default.svc.cluster.local:9092
  TOPIC_NAME: test
  USERNAME: user1
metadata:
  name: location-consumer-env