apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_geoconnections"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres-geoconnections"
  DB_PORT: "5432"
  KAFKA_SERVER: kafka:29092
  TOPIC_NAME: test
metadata:
  name: location-consumer-env