name: Message Passing - Package with Docker

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push Docker image for geoconnections 
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./modules/connection
      #     file: ./modules/connection/Dockerfile 
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/message-passing-geoconnections:latest
      
      # - name: Build and push Docker image for person 
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./modules/person
      #     file: ./modules/person/Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/message-passing-person:latest
      
      # - name: Build and push Docker image for frontend 
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./modules/frontend/
      #     file: ./modules/frontend/Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/message-passing-frontend:latest

      # - name: Build and push Docker image for location 
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./modules/location
      #     file: ./modules/location/Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/message-passing-location:latest

      # - name: Build and push Docker image for location-consumer 
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./modules/location-consumer
      #     file: ./modules/location-consumer/Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/message-passing-location-consumer:latest
